config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :referrals

  devise_for :users
  root "pages#home"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/referral.rb
class Referral < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/referrals_controller.rb
class ReferralsController < InheritedResources::Base
  before_action :set_referral, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @referrals = Referral.all
    respond_with(@referrals)
  end

  def show
    respond_with(@referral)
  end

  def new
    @referral = Referral.new
    respond_with(@referral)
  end

  def edit
  end

  def create
    @referral = Referral.new(referral_params)
    @referral.user_id = current_user.id
    @referral.save
    respond_with(@referral)
  end

  def update
    @referral.update(referral_params)
    respond_with(@referral)
  end

  def destroy
    @referral.destroy
    respond_with(@referral)
  end

  private
    def set_referral
      @referral = Referral.find(params[:id])
    end

    def referral_params
      params.require(:referral).permit(:company_name, :contact_name, :contact_email, :contact_mobile, :phone, :message, :machine_brand, :machine_weightclass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotTipApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

  <h1>HOT TIP APP</h1>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
home.html.erb

app/views/referrals/_form.html.erb
<%= form_for(@referral) do |f| %>
  <% if @referral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@referral.errors.count, "error") %> prohibited this referral from being saved:</h2>

      <ul>
      <% @referral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :contact_mobile %><br>
    <%= f.text_field :contact_mobile %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :machine_brand %><br>
    <%= f.text_field :machine_brand %>
  </div>
  <div class="field">
    <%= f.label :machine_weightclass %><br>
    <%= f.text_field :machine_weightclass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/referrals/edit.html.erb
<h1>Editing referral</h1>

<%= render 'form' %>

<%= link_to 'Show', @referral %> |
<%= link_to 'Back', referrals_path %>

app/views/referrals/index.html.erb
<h1>Listing referrals</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company name</th>
      <th>Contact name</th>
      <th>Contact email</th>
      <th>Contact mobile</th>
      <th>Phone</th>
      <th>Message</th>
      <th>Machine brand</th>
      <th>Machine weightclass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referrals.each do |referral| %>
      <tr>
        <td><%= referral.user_id %></td>
        <td><%= referral.company_name %></td>
        <td><%= referral.contact_name %></td>
        <td><%= referral.contact_email %></td>
        <td><%= referral.contact_mobile %></td>
        <td><%= referral.phone %></td>
        <td><%= referral.message %></td>
        <td><%= referral.machine_brand %></td>
        <td><%= referral.machine_weightclass %></td>
        <td><%= link_to 'Show', referral %></td>
        <td><%= link_to 'Edit', edit_referral_path(referral) %></td>
        <td><%= link_to 'Destroy', referral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referral', new_referral_path %>

app/views/referrals/new.html.erb
<h1>New referral</h1>

<%= render 'form' %>

<%= link_to 'Back', referrals_path %>

app/views/referrals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @referral.user_id %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @referral.company_name %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @referral.contact_name %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @referral.contact_email %>
</p>

<p>
  <strong>Contact mobile:</strong>
  <%= @referral.contact_mobile %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @referral.phone %>
</p>

<p>
  <strong>Message:</strong>
  <%= @referral.message %>
</p>

<p>
  <strong>Machine brand:</strong>
  <%= @referral.machine_brand %>
</p>

<p>
  <strong>Machine weightclass:</strong>
  <%= @referral.machine_weightclass %>
</p>

<%= link_to 'Edit', edit_referral_path(@referral) %> |
<%= link_to 'Back', referrals_path %>